### ISSUE TITLE
我想加个按钮让每一张图片点击跳转到其他网站

### ISSUE THREAD

**Issue by DAHE-JINYI** [hakadao/ArknightsParallaxCarousel#2]
试图在轮播图标题里加 <a> 标签，能显示但点不动。

我太菜了 Orz

**Comment by hakadao** [comment]
今天我有空的話回去看看，一段時間沒看過這份專案了
orz

**Comment by hakadao** [comment]
剛剛看了一下實現起來並不複雜，是不是你加的地方有問題？方便放一下你的代碼片段嗎？

**Comment by hakadao** [comment]
先关闭问题了，如果有相应的代码片段请附加到问题里，这样好排查
